name: e-commerce

services:
  backend:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: backend
    ports:
      -"8000:8000"

  db:
    image: postgres:16   
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      -"5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      -"6379:6379"


#docker run -it --name=postgres e pass user db 5432:5432 postgres
# to run this [docker compose up]

# there is no need to expose the port of db and redis 
# so we can remove it but we have to expose backend port

